// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYFeZYiXLmUdUxskYJ5L3GD_fSJ5tzP8',
    appId: '1:656252840041:web:8869275b60322e221a9af8',
    messagingSenderId: '656252840041',
    projectId: 'scholarsync-f0abf',
    authDomain: 'scholarsync-f0abf.firebaseapp.com',
    storageBucket: 'scholarsync-f0abf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIaw32qiu_AgZHtJCJDZ8fJamJrMWQCc',
    appId: '1:656252840041:android:e133fc52e58b962f1a9af8',
    messagingSenderId: '656252840041',
    projectId: 'scholarsync-f0abf',
    storageBucket: 'scholarsync-f0abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwbqLH-HX6cNhpz_f9rJeylhEY3NYG4c',
    appId: '1:656252840041:ios:6d9c36ece08256b61a9af8',
    messagingSenderId: '656252840041',
    projectId: 'scholarsync-f0abf',
    storageBucket: 'scholarsync-f0abf.firebasestorage.app',
    iosBundleId: 'com.example.scholarsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwbqLH-HX6cNhpz_f9rJeylhEY3NYG4c',
    appId: '1:656252840041:ios:6d9c36ece08256b61a9af8',
    messagingSenderId: '656252840041',
    projectId: 'scholarsync-f0abf',
    storageBucket: 'scholarsync-f0abf.firebasestorage.app',
    iosBundleId: 'com.example.scholarsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLYFeZYiXLmUdUxskYJ5L3GD_fSJ5tzP8',
    appId: '1:656252840041:web:5aa17ea4bd3b12931a9af8',
    messagingSenderId: '656252840041',
    projectId: 'scholarsync-f0abf',
    authDomain: 'scholarsync-f0abf.firebaseapp.com',
    storageBucket: 'scholarsync-f0abf.firebasestorage.app',
  );

}